### ISSUE TITLE
What kind of data format does the novatel_span_driver need

### ISSUE THREAD

**Issue by weisongwen** [ros-drivers/novatel_span_driver#23]
What kind of data format does the novatel_span_driver need? 
in Binary format or Assic format?

**Comment by icolwell** [comment]
Hi @weisongwen, the driver _should_ work for any novatel SPAN device running OEM6 or OEM7 firmware.
I've emphasized `should` because not every device has been tested and proven.

The driver works with a [couple data types](https://github.com/ros-drivers/novatel_span_driver/tree/master/novatel_msgs/msg) coming from the novatel devices. See the [OEM6 Firmware](https://www.novatel.com/assets/Documents/Manuals/om-20000129.pdf) guide for details on the data format and message types.

**Comment by weisongwen** [comment]
Hi, @icolwell 
Thanks for your reply! I successfully get the data from the SPAN-CPT with your driver code. 
there was something wrong with my message output from SPAN-CPT, and I re-configured the parameters of Span-CPT.
Thanks

**Comment by icolwell** [comment]
That is good to hear! Next time please open a single issue instead of posting to many unrelated issues and PRs.

**Comment by weisongwen** [comment]
@icolwell  well noted here. Thanks a lot!
