### ISSUE TITLE
IOError: [Errno 22] Invalid argument using serial_connection

### ISSUE THREAD

**Issue by Durant35** [ros-drivers/novatel_span_driver#45]
+ Version: https://github.com/ros-drivers/novatel_span_driver/tree/serial_connection
+ Error info:
![WeChat Image_20190811165604](https://user-images.githubusercontent.com/6770853/62831929-317e9000-bc59-11e9-82aa-3785c0770442.jpg)

**Comment by JWhitleyAStuff** [comment]
@Durant35 - It looks like you're trying to use the Serial branch of this driver. That branch is untested and has not been updated in a long time. If you are a developer, we would be welcome to having you add some fixes to this branch. Otherwise, please try using https://github.com/swri-robotics/novatel_gps_driver with the serial option. This driver has been tested and works correctly with serial connections.

**Comment by Durant35** [comment]
+ seems fine during off-vehicle testing, using a common usb-serial device...
![image](https://user-images.githubusercontent.com/6770853/62929903-f82b5900-bded-11e9-99b0-9e16d7b8a391.png)

**Comment by Durant35** [comment]
@JWhitleyAStuff  bug fixed during field test, and shall we make a pull request to merge the `serial_connection` branch into `master`?
![微信图片_20190814200255](https://user-images.githubusercontent.com/6770853/63019721-c3430300-bece-11e9-8595-3979d13fb5c3.jpg)

**Comment by JWhitleyAStuff** [comment]
Yes, please!
